name: flutree
description: Profile links builder.

publish_to: "none"

version: 4.1.3+36

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1
  dough: ^2.0.0
  fluttertoast: ^8.2.8
  flutter_markdown: ^0.6.18+1
  firebase_core: ^3.6.0
  google_mobile_ads: ^5.1.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  flutter_facebook_auth: ^7.1.1
  crypto: ^3.0.3
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  firebase_dynamic_links: ^6.1.10
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  share_plus: ^10.1.2
  package_info_plus: ^8.1.1
  qr_flutter: ^4.1.0
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_svg: ^2.0.9
  gal: ^2.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - images/sample.jpg
    # - images/intro.gif
    - images/logo/

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "images/logo/vlag_app.png"
    background_color: "#000000"
    theme_color: "#1DB877"
  image_path: "images/logo/vlag_app.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/logo/vlag_app.png"
  remove_alpha_ios: true
  min_sdk_android: 21

dependency_overrides:
  archive: ^4.0.7
